version: "2"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 28017:27017
    volumes:
      - ./data/db:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - mongo
  backend:
    build: ./back
    environment:
      APP_NAME: rpg-hub:server
      DEBUG: rpg-hub:*
      PORT: 4000
      MONGO_URI: mongodb://mongo/august
    ports:
      - 4000:4000
    links:
      - mongo
    volumes:
      - ./back/package.json:/app/package.json
      - ./back/node_modules:/app/node_modules
      - ./back/dist:/app/dist
      - ./front/public:/app/public
      - ./back/src:/app/src
  frontend:
    # restart: always
    build: ./front
    ports:
      - "8080:8080"
    links:
      - backend
    volumes:
      - ./front/package.json:/app/package.json
      - ./front/node_modules:/app/node_modules
      - ./front/dist:/app/dist
      - ./front/public:/app/public
      - ./front/src:/app/src
