version: "2"
services:
  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 28017:27017
  #   volumes:
  #     - ./data/db:/data/db
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   links:
  #     - mongo
  # backend:
  #   restart: always
  #   build: ./back
  #   environment:
  #     APP_NAME: august:server
  #     DEBUG: august:*
  #     PORT: 4000
  #     MONGO_URI: mongodb://mongo/august
  #   ports:
  #     - 4000:4000
  #   links:
  #     - mongo
  #   volumes:
  #     - ./back/package.json:/usr/src/app/package.json
  #     - ./back/node_modules:/usr/src/app/node_modules
  #     - ./back/dist:/usr/src/app/dist
  #     - ./front/public:/usr/src/app/public
  #     - ./back/src:/usr/src/app/src
  frontend:
    # restart: always
    build: ./front
    ports:
      - "8080:8080"
    # links:
    #   - backend
    volumes:
      - ./front/package.json:/app/package.json
      - ./front/node_modules:/app/node_modules
      - ./front/dist:/app/dist
      - ./front/public:/app/public
      - ./front/src:/app/src
